defaultSemverRangePrefix: ''

npmScopes:
  lottiefiles:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '*'
  eslint-module-utils@*:
    dependencies:
      '@typescript-eslint/parser': '*'
      eslint: '*'
      resolve: '*'
    peerDependencies:
      eslint-import-resolver-node: '*'
  '@lottiefiles/eslint-plugin@*':
    peerDependenciesMeta:
      'graphql':
        optional: true
      'jest':
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

preferInteractive: true
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
