name: Release
on:
  push:
    branches: [main]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets
          # can generate changelogs with the correct commits.
          fetch-depth: 0

      # If you use a version of Node other than 14, change it here.
      - name: Set up Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      # If you use npm instead of yarn, change this to `npm install`.
      - name: Install dependencies
        run: yarn

      # Change this to customize your lint command.
      - name: Lint
        run: yarn lint

      # Change this to customize your test command.
      #- name: Test
      #  run: yarn test

      # Change this to customize your build command.
      - name: Build
        run: yarn build

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to github
        id: changesets
        uses: changesets/action@master
        with:
          version: yarn changeset version
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
